function init_sici_fig(app)

% if there is already a sici fig, clear old axes & fit info
if ~isempty(findobj('Name', 'SICI & ICF'))
	app.sici_axes;
	
	% clear any existing fit_info
	app.sici_info = [];
	% reset ui
	ylabel('MEP Vp-p (µV)')
	app.sici_info.edNormFactor.String = '1';
	app.sici_info.mean_ts.String = '0';
	app.sici_info.sd_ts.String = '0';
	app.sici_info.n_ts.String = '0';
	app.sici_info.mean_sici.String = '0';
	app.sici_info.sd_sici.String = '0';
	app.sici_info.n_sici.String = '0';
	app.sici_info.mean_icf.String = '';
	app.sici_info.sd_icf.String = '';
	app.sici_info.n_icf.String = '0';

	
else

	app.sici_fig = figure('Position', [1544 542 506 505], ...
		'NumberTitle', 'off', 'Name', 'SICI & ICF', ...
		'MenuBar', 'none', 'ToolBar', 'none');


	app.sici_axes = axes('Position', [0.16 0.3 0.775 0.6], ...
		'Fontsize', 20, 'xlim', [0.5 3.5], 'xtick', 1:3, 'xticklabel', {'TS', 'SICI', 'ICF'});
	ylabel('MEP Vp-p (µV)')
	% xlabel('Stim Type')


	% userdata is a table with the data
	app.sici_axes.UserData = cell2table(cell(0,4), ...
		'VariableNames', {'Epoch', 'Use', 'MagStim_Setting', 'MEPAmpl_uVPp'});

	% button to compute curve fit
	% h = uicontrol(app.sici_fig, 'Style', 'pushbutton', ...
	% 			'String', 'Compute Mean & SD', ...
	% 			'Units', 'normalized', ...
	% 			'Position', [0.35 0.019 0.4 0.06], ...
	% 			'Fontsize', 16, ...
	% 			'Callback', {@sici_mean, app});

	% button to save datapoints
	h_save = uicontrol(app.sici_fig, 'Style', 'pushbutton', ...
				'String', 'Save', ...
				'Units', 'normalized', ...
				'Position', [0.75 0.019 0.2 0.06], ...
				'Fontsize', 16, ...
				'Tag', 'pushbutton', ...
				'Callback', {@save_and_close_sici, app});

	% button to print as png
	h_print = uicontrol(app.sici_fig, 'Style', 'pushbutton', ...
				'String', 'P', ...
				'Units', 'normalized', ...
				'Position', [0.95 0.03 0.04 0.04], ...
				'Fontsize', 8, ...
				'Callback', {@print_sici, app});
	
	
	% set a close function to save the data
	app.sici_fig.CloseRequestFcn = {@save_and_close_sici, app};

	app.sici_popmenu = uicontrol(app.sici_fig, 'style','popup', ...
		'string',{'Test Stim';'SICI';'ICF'}, ...
		'Units', 'normalized', ...
		'Position', [0.10 0.015 0.25 0.07], ...
		'FontSize', 16);

	
	% % mean
	uicontrol(app.sici_fig, ...
		'Style', 'text', ...
		'String', 'Mean', ...
		'Units', 'normalized', ...
		'Position', [0.04 0.19 0.149 0.04], ...
		'FontSize', 14);

	app.sici_info.ts_mean = uicontrol(app.sici_fig, ...
		'Style', 'text', ...
		'String', '0', ...
		'Units', 'normalized', ...
		'Position', [0.22 0.19 0.122 0.04], ...
		'FontSize', 14);
	app.sici_info.sici_mean = uicontrol(app.sici_fig, ...
		'Style', 'text', ...
		'String', '0', ...
		'Units', 'normalized', ...
		'Position', [0.49 0.19 0.122 0.04], ...
		'FontSize', 14);
	app.sici_info.icf_mean = uicontrol(app.sici_fig, ...
		'Style', 'text', ...
		'String', '0', ...
		'Units', 'normalized', ...
		'Position', [0.75 0.19 0.122 0.04], ...
		'FontSize', 14);
	

	% % std dev
	uicontrol(app.sici_fig, ...
		'Style', 'text', ...
		'String', 'SD', ...
		'Units', 'normalized', ...
		'Position', [0.04 0.15 0.149 0.04], ...
		'FontSize', 14);

	app.sici_info.ts_sd = uicontrol(app.sici_fig, ...
		'Style', 'text', ...
		'String', '0', ...
		'Units', 'normalized', ...
		'Position', [0.22 0.15 0.122 0.04], ...
		'FontSize', 14);
	app.sici_info.sici_sd = uicontrol(app.sici_fig, ...
		'Style', 'text', ...
		'String', '0', ...
		'Units', 'normalized', ...
		'Position', [0.49 0.15 0.122 0.04], ...
		'FontSize', 14);
	app.sici_info.icf_sd = uicontrol(app.sici_fig, ...
		'Style', 'text', ...
		'String', '0', ...
		'Units', 'normalized', ...
		'Position', [0.75 0.15 0.122 0.04], ...
		'FontSize', 14);
	% % N
	uicontrol(app.sici_fig, ...
		'Style', 'text', ...
		'String', 'N', ...
		'Units', 'normalized', ...
		'Position', [0.04 0.11 0.149 0.04], ...
		'FontSize', 14);

	app.sici_info.ts_n = uicontrol(app.sici_fig, ...
		'Style', 'text', ...
		'String', '0', ...
		'Units', 'normalized', ...
		'Position', [0.22 0.11 0.122 0.04], ...
		'FontSize', 14);
	app.sici_info.sici_n = uicontrol(app.sici_fig, ...
		'Style', 'text', ...
		'String', '0', ...
		'Units', 'normalized', ...
		'Position', [0.49 0.11 0.122 0.04], ...
		'FontSize', 14);
	app.sici_info.icf_n = uicontrol(app.sici_fig, ...
		'Style', 'text', ...
		'String', '0', ...
		'Units', 'normalized', ...
		'Position', [0.75 0.11 0.122 0.04], ...
		'FontSize', 14);
	%{
	app.sici_info.edMEPmax = uicontrol(app.rc_fig, ...
		'Style', 'edit', ...
		'String', '', ...
		'Units', 'normalized', ...
		'Position', [0.604 0.115 0.122 0.032], ...
		'FontSize', 12);
	
	app.sici_info.edMEPmin = uicontrol(app.rc_fig, ...
		'Style', 'edit', ...
		'String', '', ...
		'Units', 'normalized', ...
		'Position', [0.04 0.115 0.122 0.032], ...
		'FontSize', 12);
	
	app.sici_info.edMEPval = uicontrol(app.rc_fig, ...
		'Style', 'edit', ...
		'String', '', ...
		'Units', 'normalized', ...
		'Position', [0.04 0.03 0.122 0.032], ...
		'FontSize', 12, ...
		'Callback', {@rc_change_mep_val, app});
	
	app.sici_info.editStimval = uicontrol(app.rc_fig, ...
		'Style', 'edit', ...
		'String', '', ...
		'Units', 'normalized', ...
		'Position', [0.187 0.03 0.122 0.032], ...
		'FontSize', 12, ...
		'Callback', {@rc_change_stim_val, app});
	

	app.sici_info.txtSlopeCI = uicontrol(app.rc_fig, ...
		'Style', 'text', ...
		'String', '[x, x]', ...
		'Units', 'normalized', ...
		'Position', [0.165 0.085 0.172 0.027]);


	app.sici_info.txtS50CI = uicontrol(app.rc_fig, ...
		'Style', 'text', ...
		'String', '[x, x]', ...
		'Units', 'normalized', ...
		'Position', [0.379 0.085 0.172 0.027]);

	
	app.sici_info.txtMEPmaxCI = uicontrol(app.rc_fig, ...
		'Style', 'text', ...
		'String', '[x, x]', ...
		'Units', 'normalized', ...
		'Position', [0.576 0.085 0.172 0.027]);

	app.sici_info.txtRsq = uicontrol(app.rc_fig, ...
		'Style', 'text', ...
		'String', 'Rsq = 0.0', ...
		'Units', 'normalized', ...
		'Position', [0.767 0.1 0.2 0.07], ...
		'FontSize', 15);

	app.sici_info.txtAUC = uicontrol(app.rc_fig, ...
		'Style', 'text', ...
		'String', 'AUC = 0.0', ...
		'Units', 'normalized', ...
		'Position', [0.767 0.085 0.229 0.027]);
	%}
end

