function init_rc_fig(app)

app.rc_fig = figure('Position', [200   200   600   800], ...
	'NumberTitle', 'off', 'Name', 'Recruitment Curve');

app.rc_axes = axes('Position', [0.13 0.4 0.775 0.55]);
ylabel('MEP Vp-p (µV)')
xlabel('Magstim Power')

% button to compute curve fit
h = uicontrol(app.rc_fig, 'Style', 'pushbutton', ...
			'String', 'Compute Curve Fit', ...
			'Units', 'normalized', ...
			'Position', [0.35 0.03 0.4 0.05], ...
			'Fontsize', 20, ...
			'Callback', @boltzman_fit)
