function init_disp_axes(app)
% init the axes to display the emg data

app.h_disp_emg_axes = axes('FontSize', 16);
ylabel('EMG (µV)')
xlabel('Time (msec)')


seg_time = (app.params.postTriggerTime + app.params.preTriggerTime) / 1000;
seg_num_points = round(app.params.sampFreq*seg_time);
t = (0:1/app.params.sampFreq:(seg_time-1/app.params.sampFreq))*1000 - app.params.preTriggerTime;

% data line
app.h_emg_line = line(app.h_disp_emg_axes, t, zeros(1, seg_num_points), ...
  'LineWidth', 3) ;

% lines at x,y = 0,0
line(app.h_disp_emg_axes, app.h_disp_emg_axes.XLim, [0 0]);
line(app.h_disp_emg_axes, [0 0], [-1e6 1e6]);

% min & max vertical lines - draggable
app.h_t_min_line = line(app.h_disp_emg_axes, [15 15], [-1e6 1e6], ...
  'LineWidth', 2, 'Color', [0 0.9 0]);
draggable(app.h_t_min_line, 'h', [0 200]);
app.h_t_max_line = line(app.h_disp_emg_axes, [90 90], [-1e6 1e6], ...
  'LineWidth', 2, 'Color', [0 0.9 0]);
draggable(app.h_t_max_line, 'h', [0 200]);

% text display of MEP amplitude
app.mep_value_text = uicontrol(app.emg_data_fig, 'Style', 'text', ...
			'String', num2str(1000), ...
			'Units', 'normalized', ...
			'Position', [0.7 0.85 0.29 0.14], ...
			'Fontsize', 50, 'ForegroundColor', 'b');

% text display of pre-emg value
app.pre_emg_text = uicontrol(app.emg_data_fig, 'Style', 'text', ...
			'String', num2str(0), ...
			'Units', 'normalized', ...
			'Position', [0.135 0.11 0.23 0.07], ...
			'Fontsize',18, 'ForegroundColor', 'b');
		
% edit boxes for min  & max x-axis values
app.xmin_edit = uicontrol(app.emg_data_fig, 'Style', 'edit', ...
			'String', num2str(-100), ...
			'Units', 'normalized', ...
			'Position', [0.08 0.048 0.11 0.06], ...
			'Fontsize',15, ...
			'Tag', 'edit_xmin', ...
			'Callback', {@edit_xlims, app});

app.xmax_edit = uicontrol(app.emg_data_fig, 'Style', 'edit', ...
			'String', num2str(200), ...
			'Units', 'normalized', ...
			'Position', [0.85 0.048 0.11 0.06], ...
			'Fontsize',15, ...
			'Tag', 'edit_xmax', ...
			'Callback', {@edit_xlims, app});
		
app.sample_num_text = uicontrol(app.emg_data_fig, 'Style', 'text', ...
			'String', num2str(0), ...
			'Units', 'normalized', ...
			'Position', [0.08 0.021 0.09 0.03], ...
			'Fontsize',11, ...
			'Tag', 'sample_num_text');

app.active_sample_checkbox = uicontrol(app.emg_data_fig, 'Style', 'checkbox', ...
			'Value', 1, ...
			'Units', 'normalized', ...
			'Position', [0.075 0.017 0.03 0.03], ...
			'Tag', 'active_sample_checkbox', ...
			'Callback', {@activate_deactivate_sample, app});

app.next_sample_pushbutton = uicontrol(app.emg_data_fig, 'Style', 'pushbutton', ...
			'String', '>', ...
			'Fontsize',11, ...
			'Units', 'normalized', ...
			'Position', [0.16 0.015 0.03 0.03], ...
			'Tag', 'next_sample_pushbutton', ...
			'Callback', {@get_emgdata_sample, app});

app.previous_sample_pushbutton = uicontrol(app.emg_data_fig, 'Style', 'pushbutton', ...
			'String', '<', ...
			'Fontsize',11, ...
			'Units', 'normalized', ...
			'Position', [0.035 0.015 0.03 0.03], ...
			'Tag', 'previous_sample_pushbutton', ...
			'Callback', {@get_emgdata_sample, app});

% set a close function to uncheck the display MEP checkbox
app.emg_data_fig.CloseRequestFcn = {@close_mep_fig, app};
