function init_rc_fig(app)

app.rc_fig = figure('Position', [200   200   600   800], ...
	'NumberTitle', 'off', 'Name', 'Recruitment Curve');


app.rc_axes = axes('Position', [0.13 0.4 0.775 0.55]);
ylabel('MEP Vp-p (µV)')
xlabel('Magstim Power')

% userdata is a table with the data
app.rc_axes.UserData = cell2table(cell(0,4), ...
	'VariableNames', {'Epoch', 'Use', 'MagStim_Setting', 'MEPAmpl_uVPp'});

% button to compute curve fit
h = uicontrol(app.rc_fig, 'Style', 'pushbutton', ...
			'String', 'Compute Curve Fit', ...
			'Units', 'normalized', ...
			'Position', [0.35 0.03 0.4 0.05], ...
			'Fontsize', 20, ...
			'Callback', {@rc_boltzman_fit, app});

% set a close function to save the data
app.rc_fig.CloseRequestFcn = {@save_and_close_rc, app};

% labels
uicontrol(app.rc_fig, ...
	'Style', 'text', ...
	'String', 'Slope, m', ...
	'Units', 'normalized', ...
	'Position', [0.163 0.326 0.149 0.027]);
uicontrol(app.rc_fig, ...
	'Style', 'text', ...
	'String', 'S_50', ...
	'Units', 'normalized', ...
	'Position', [0.415 0.326 0.094 0.027]);
uicontrol(app.rc_fig, ...
	'Style', 'text', ...
	'String', 'MEP_max', ...
	'Units', 'normalized', ...
	'Position', [0.597 0.326 0.141 0.027]);
uicontrol(app.rc_fig, ...
	'Style', 'text', ...
	'String', 'Initial', ...
	'Units', 'normalized', ...
	'Position', [0.038 0.296 0.094 0.027]);
uicontrol(app.rc_fig, ...
	'Style', 'text', ...
	'String', 'Fit', ...
	'Units', 'normalized', ...
	'Position', [0.036 0.243 0.107 0.027]);
uicontrol(app.rc_fig, ...
	'Style', 'text', ...
	'String', 'Confidence', ...
	'Units', 'normalized', ...
	'Position', [0.0 0.204 0.172 0.027]);
uicontrol(app.rc_fig, ...
	'Style', 'text', ...
	'String', 'Interval', ...
	'Units', 'normalized', ...
	'Position', [0.011 0.185 0.147 0.027]);


% fitting input parameters
app.rc_fit_info.edSlope = uicontrol(app.rc_fig, ...
	'Style', 'edit', ...
	'String', '0.1', ...
	'Units', 'normalized', ...
	'Position', [0.177 0.294 0.122 0.032]);
app.rc_fit_info.edS50 = uicontrol(app.rc_fig, ...
	'Style', 'edit', ...
	'String', '50', ...
	'Units', 'normalized', ...
	'Position', [0.398 0.294 0.122 0.032]);
app.rc_fit_info.edMEPmax = uicontrol(app.rc_fig, ...
	'Style', 'edit', ...
	'String', '500', ...
	'Units', 'normalized', ...
	'Position', [0.604 0.294 0.122 0.032]);

% fitting output parameters
app.rc_fit_info.txtSlope = uicontrol(app.rc_fig, ...
	'Style', 'text', ...
	'String', '', ...
	'Units', 'normalized', ...
	'Position', [0.199 0.243 0.107 0.027]);
app.rc_fit_info.txtS50 = uicontrol(app.rc_fig, ...
	'Style', 'text', ...
	'String', '', ...
	'Units', 'normalized', ...
	'Position', [0.413 0.243 0.107 0.027]);
app.rc_fit_info.txtMEPmax = uicontrol(app.rc_fig, ...
	'Style', 'text', ...
	'String', '', ...
	'Units', 'normalized', ...
	'Position', [0.609 0.243 0.107 0.027]);

app.rc_fit_info.txtSlopeCI1 = uicontrol(app.rc_fig, ...
	'Style', 'text', ...
	'String', '', ...
	'Units', 'normalized', ...
	'Position', [0.165 0.212 0.172 0.027]);
app.rc_fit_info.txtSlopeCI2 = uicontrol(app.rc_fig, ...
	'Style', 'text', ...
	'String', '', ...
	'Units', 'normalized', ...
	'Position', [0.165 0.185 0.172 0.027]);

app.rc_fit_info.txtS50CI1 = uicontrol(app.rc_fig, ...
	'Style', 'text', ...
	'String', '', ...
	'Units', 'normalized', ...
	'Position', [0.379 0.212 0.172 0.027]);
app.rc_fit_info.txtS50CI2 = uicontrol(app.rc_fig, ...
	'Style', 'text', ...
	'String', '', ...
	'Units', 'normalized', ...
	'Position', [0.379 0.185 0.172 0.027]);

app.rc_fit_info.txtMEPmaxCI1 = uicontrol(app.rc_fig, ...
	'Style', 'text', ...
	'String', '', ...
	'Units', 'normalized', ...
	'Position', [0.576 0.212 0.172 0.027]);
app.rc_fit_info.txtMEPmaxCI2 = uicontrol(app.rc_fig, ...
	'Style', 'text', ...
	'String', '', ...
	'Units', 'normalized', ...
	'Position', [0.576 0.185 0.172 0.027]);

app.rc_fit_info.txtRsq = uicontrol(app.rc_fig, ...
	'Style', 'text', ...
	'String', '', ...
	'Units', 'normalized', ...
	'Position', [0.767 0.295 0.189 0.027]);

app.rc_fit_info.txtAUC = uicontrol(app.rc_fig, ...
	'Style', 'text', ...
	'String', '', ...
	'Units', 'normalized', ...
	'Position', [0.767 0.227 0.229 0.027]);




