function init_datapoint_table(app, tbl)

% col 2 = Use = logical
tbl.Use = logical(tbl.Use);

% headers = {'Epochs', 'Use', ...
%            '<html><center>MagStim<br />Setting</center></html>', ...
%            '<html><center>MEPAmpl<br />uVPp</center></html>', ...
%            '<html><center>PreStimEmg<br />100ms</center></html>', ...
%            '<html><center>MonitorEMG<br />val</center></html>', ...
%            '<html><center>Gain/Goal<br />EMG</center></html>', ...
%            '<html><center>Goal<br />Min</center></html>', ...
%            '<html><center>Goal<br />Max</center></html>'};
headers = {'Epochs', 'Use', ...
           'MagStim\nSetting', ...
           '<html><center>MEPAmpl<br />uVPp</center></html>', ...
           '<html><center>PreStimEmg<br />100ms</center></html>', ...
           '<html><center>MonitorEMG<br />val</center></html>', ...
           '<html><center>Gain/Goal<br />EMG</center></html>', ...
           '<html><center>Goal<br />Min</center></html>', ...
           '<html><center>Goal<br />Max</center></html>'};

app.UITable.Data = tbl;
app.UITable.ColumnName = headers';
app.UITable.ColumnWidth = {60, 30, 'auto', 'auto', 'auto', 'auto', 'auto', 'auto', 'auto'};
keyboard