function init_sici_fig(app)

% if there is already a sici fig, clear old axes & fit info
if ~isempty(findobj('Name', 'SICI & ICF'))
	app.sici_axes;
	
	% clear any existing fit_info
	app.sici_info = [];
	% reset ui
	ylabel('MEP Vp-p (µV)')
	app.sici_info.edNormFactor.String = '1';
	app.sici_info.mean_ts.String = '0';
	app.sici_info.sd_ts.String = '0';
	app.sici_info.n_ts.String = '0';
	app.sici_info.mean_sici.String = '0';
	app.sici_info.sd_sici.String = '0';
	app.sici_info.n_sici.String = '0';
	app.sici_info.mean_icf.String = '';
	app.sici_info.sd_icf.String = '';
	app.sici_info.n_icf.String = '0';

	
else

	app.sici_fig = figure('Position', [1544 542 506 505], ...
		'NumberTitle', 'off', 'Name', 'SICI & ICF', ...
		'MenuBar', 'none', 'ToolBar', 'none');


	app.sici_axes = axes('Position', [0.16 0.3 0.775 0.6], ...
		'Fontsize', 20, 'xlim', [0.5 3.5], 'xtick', 1:3, 'xticklabel', {'TS', 'SICI', 'ICF'});
	ylabel('MEP Vp-p (µV)')
	% xlabel('Stim Type')


	% userdata is a table with the data
	app.sici_axes.UserData = cell2table(cell(0,4), ...
		'VariableNames', {'Epoch', 'Use', 'MagStim_Setting', 'MEPAmpl_uVPp'});

	% button to compute curve fit
	% h = uicontrol(app.sici_fig, 'Style', 'pushbutton', ...
	% 			'String', 'Compute Mean & SD', ...
	% 			'Units', 'normalized', ...
	% 			'Position', [0.35 0.019 0.4 0.06], ...
	% 			'Fontsize', 16, ...
	% 			'Callback', {@sici_mean, app});

	% button to save datapoints
	h_save = uicontrol(app.sici_fig, 'Style', 'pushbutton', ...
				'String', 'Save', ...
				'Units', 'normalized', ...
				'Position', [0.75 0.019 0.2 0.06], ...
				'Fontsize', 16, ...
				'Tag', 'pushbutton', ...
				'Callback', {@save_and_close_sici, app});

	% button to print as png
	h_print = uicontrol(app.sici_fig, 'Style', 'pushbutton', ...
				'String', 'P', ...
				'Units', 'normalized', ...
				'Position', [0.95 0.03 0.04 0.04], ...
				'Fontsize', 8, ...
				'Callback', {@print_sici, app});
	
	
	% set a close function to save the data
	app.sici_fig.CloseRequestFcn = {@save_and_close_sici, app};

	app.sici_popmenu = uicontrol(app.sici_fig, 'style','popup', ...
		'string',{'Test Stim';'SICI';'ICF'}, ...
		'Units', 'normalized', ...
		'Position', [0.10 0.015 0.25 0.07], ...
		'FontSize', 16);

	
	% % mean
	uicontrol(app.sici_fig, ...
		'Style', 'text', ...
		'String', 'Mean', ...
		'Units', 'normalized', ...
		'Position', [0.04 0.19 0.149 0.04], ...
		'FontSize', 14);

	app.sici_ui.ts_mean = uicontrol(app.sici_fig, ...
		'Style', 'text', ...
		'String', '0', ...
		'Units', 'normalized', ...
		'Position', [0.22 0.19 0.122 0.04], ...
		'FontSize', 14);
	app.sici_ui.sici_mean = uicontrol(app.sici_fig, ...
		'Style', 'text', ...
		'String', '0', ...
		'Units', 'normalized', ...
		'Position', [0.49 0.19 0.122 0.04], ...
		'FontSize', 14);
	app.sici_ui.icf_mean = uicontrol(app.sici_fig, ...
		'Style', 'text', ...
		'String', '0', ...
		'Units', 'normalized', ...
		'Position', [0.75 0.19 0.122 0.04], ...
		'FontSize', 14);
	

	% % std dev
	uicontrol(app.sici_fig, ...
		'Style', 'text', ...
		'String', 'SD', ...
		'Units', 'normalized', ...
		'Position', [0.04 0.15 0.149 0.04], ...
		'FontSize', 14);

	app.sici_ui.ts_sd = uicontrol(app.sici_fig, ...
		'Style', 'text', ...
		'String', '0', ...
		'Units', 'normalized', ...
		'Position', [0.22 0.15 0.122 0.04], ...
		'FontSize', 14);
	app.sici_ui.sici_sd = uicontrol(app.sici_fig, ...
		'Style', 'text', ...
		'String', '0', ...
		'Units', 'normalized', ...
		'Position', [0.49 0.15 0.122 0.04], ...
		'FontSize', 14);
	app.sici_ui.icf_sd = uicontrol(app.sici_fig, ...
		'Style', 'text', ...
		'String', '0', ...
		'Units', 'normalized', ...
		'Position', [0.75 0.15 0.122 0.04], ...
		'FontSize', 14);
	% % N
	uicontrol(app.sici_fig, ...
		'Style', 'text', ...
		'String', 'N', ...
		'Units', 'normalized', ...
		'Position', [0.04 0.11 0.149 0.04], ...
		'FontSize', 14);

	app.sici_ui.ts_n = uicontrol(app.sici_fig, ...
		'Style', 'text', ...
		'String', '0', ...
		'Units', 'normalized', ...
		'Position', [0.22 0.11 0.122 0.04], ...
		'FontSize', 14);
	app.sici_ui.sici_n = uicontrol(app.sici_fig, ...
		'Style', 'text', ...
		'String', '0', ...
		'Units', 'normalized', ...
		'Position', [0.49 0.11 0.122 0.04], ...
		'FontSize', 14);
	app.sici_ui.icf_n = uicontrol(app.sici_fig, ...
		'Style', 'text', ...
		'String', '0', ...
		'Units', 'normalized', ...
		'Position', [0.75 0.11 0.122 0.04], ...
		'FontSize', 14);
	
	app.sici_ui.ts_mline = line([0.7 1.3],[nan nan], 'LineWidth', 3, 'Color', [0 0.4470 0.7410]);
	app.sici_ui.ts_sdupline = line([0.7 1.3],[nan nan], 'LineWidth', 3, 'Color', [0 0.4470 0.7410], 'LineStyle', '--');
	app.sici_ui.ts_sddownline = line([0.7 1.3],[nan nan], 'LineWidth', 3, 'Color', [0 0.4470 0.7410], 'LineStyle', '--');
	
	app.sici_ui.sici_mline = line([1.7 2.3],[nan nan], 'LineWidth', 3, 'Color', [0 0.4470 0.7410]);
	app.sici_ui.sici_sdupline = line([1.7 2.3],[nan nan], 'LineWidth', 3, 'Color', [0 0.4470 0.7410], 'LineStyle', '--');
	app.sici_ui.sici_sddownline = line([1.7 2.3],[nan nan], 'LineWidth', 3, 'Color', [0 0.4470 0.7410], 'LineStyle', '--');

	app.sici_ui.icf_mline = line([2.7 3.3],[nan nan], 'LineWidth', 3, 'Color', [0 0.4470 0.7410]);
	app.sici_ui.icf_sdupline = line([2.7 3.3],[nan nan], 'LineWidth', 3, 'Color', [0 0.4470 0.7410], 'LineStyle', '--');
	app.sici_ui.icf_sddownline = line([2.7 3.3],[nan nan], 'LineWidth', 3, 'Color', [0 0.4470 0.7410], 'LineStyle', '--');

end

